name: Make Windows executable

on:
  push:
    branches: ["main"]

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: sudo dpkg --add-architecture i386
      - run: sudo add-apt-repository ppa:ubuntu-wine/ppa
      - run: sudo apt-get update
      - run: sudo apt-get install wine1.8
      - run: npm install
      - run: npm run make
      - uses: actions/upload-artifact@v3
        with:
          name: win32
          path: out/